CREATE TABLE Locations (
    Id INT IDENTITY(1,1) PRIMARY KEY,
    Name NVARCHAR(255) NOT NULL,
    IPAddress NVARCHAR(100) NOT NULL
);

CREATE TABLE Tickets (
    Id INT IDENTITY(1,1) PRIMARY KEY,
    LocationId INT NOT NULL,
    ShiftName NVARCHAR(100) NOT NULL,
    Category NVARCHAR(255) NOT NULL,
    Status NVARCHAR(50) NOT NULL,
    OpenedAt DATETIME2 NOT NULL,
    ClosedAt DATETIME2 NULL
);

CREATE TABLE ChatMessages (
    Id INT IDENTITY(1,1) PRIMARY KEY,
    TicketId INT NOT NULL,
    SenderType NVARCHAR(50) NOT NULL,
    MessageText NVARCHAR(MAX) NOT NULL,
    CreatedAt DATETIME2 NOT NULL
);
